name: GitHub Actions Demo
run-name: testing GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [github-arc-runner]
    steps:
      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt-get -y install podman
      # - run: findmnt -o PROPAGATION /
      # - run: sudo mount -o remount,shared / /
      - name: Build image
        run: podman build -t navitia-explorer:latest -o type=tar,dest=/tmp/output.tar .
      - name: export image
        run : podman save navitia-explorer:latest > navitia-explorer.tar
      - run: echo "This job's status is ${{ job.status }}."
